version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: flask-app:healthy  
    container_name: flask-app
    environment:
      - PORT=5000
    ports:
      - "5050:5000"